service:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${WS_DATABASE_PORT:-5432}:5432
    enviroment:
      POSTGRES_USER: ${WS_DATABASE_USER}
      POSTGRES_PASSWORD: ${WS_DATABASE_PASSWORD}
      POSTGRES_DB: ${WS_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    # local pode ser subistituido por onde sera armazenado os arquivos, S3, drive e etc
    driver: local
